apiVersion: apps/v1
kind: Deployment
metadata:
  name: kart-challenge
  namespace: kart-challenge
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kart-challenge
  template:
    metadata:
      labels:
        app: kart-challenge
    spec:
      initContainers:
        - name: wait-for-postgres
          image: busybox
          command: ['sh', '-c', 'until nc -z postgres 5432; do echo waiting for postgres; sleep 2; done;']
      containers:
        - name: kart-challenge
          image: kart-challenge
          imagePullPolicy: IfNotPresent
          command:
            - "sh"
            - "-c"
            - ./kart-challenge --config /mnt/config/config.k8s.yaml
          ports:
            - containerPort: 8080
          volumeMounts:
            - mountPath: /mnt/config
              name: config-volume
            - mountPath: /mnt/db
              name: db-migrations-volume
            - mountPath: /mnt/promocodes
              name: promo-codes-volume
          resources:
            requests:
              cpu: "500m"
              memory: "512Mi"
            limits:
              cpu: "1"
              memory: "1Gi"
          livenessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 5
      volumes:
        - name: config-volume
          configMap:
            name: kart-config
        - name: db-migrations-volume
          hostPath:
            path: /mnt/db
            type: Directory
        - name: promo-codes-volume
          hostPath:
            path: /mnt/promocodes
            type: Directory
