apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: kart-challenge-ingress
  namespace: kart-challenge
  annotations:
    nginx.ingress.kubernetes.io/proxy-body-size: "10m"
    nginx.ingress.kubernetes.io/proxy-buffer-size: "16k"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "600"
spec:
  rules:
    - host: kart.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: kart-challenge
                port:
                  number: 80
